export const states = [
    {
        name: 'andhrapradesh',
        imgurl: "/",
        capital: 'Amaravati'
    }, {
        name: "arunachalpradesh",
        capital: "Itanagar",
        imgurl: "/"
    }, {
        name: "asam",
        capital: "dispur",
        imgurl: "/"

    }, {
        name: "bihar",
        capital: "patna",
        imgurl: "/"
    }, {
        name: "chhattisgarh",
        capital: "raipur",
        imgurl: "/"
    }, {
        name: "goa",
        capital: "panaji",
        imgurl: "/"
    }, {
        name: "gujurat",
        capital: "gandhinagar",
        imgurl: "/"
    }, {
        name: "haryana",
        capital: "chandigarh",
        imgurl: "/"
    }, {
        name: "himachalPradesh",
        capital: "shimla",
        imgurl: "/"
    }, {
        name: "jharkhand",
        capital: "ranchi",
        imgurl: "/"
    }, {
        name: "karnataka",
        capital: "bengaluru",
        imgurl: "/"
    }, {
        name: "kerala",
        capital: "thiruvanthapuram",
        imgurl: "/"
    }, {
        name: "madhyapradesh",
        capital: "bhopal",
        imgurl: "/"
    }, {
        name: "maharastra",
        capital: "mumbai",
        imgurl: "/"
    }, {
        name: "manipur",
        capital: "imphal",
        imgurl: "/"
    }, {
        name: "meghalaya",
        capital: "shilong",
        imgurl: "/"
    }, {
        name: "mizoram",
        capital: "aizwal",
        imgurl: "https://firebasestorage.googleapis.com/v0/b/heritage-site-edd7c.appspot.com/o/state%2Fmizoram.jpg?alt=media&token=321f3a70-779c-4c7d-948a-9c83137f7eab"
    }, {
        name: "nagaland",
        capital: "kohima",
        imgurl: "https://firebasestorage.googleapis.com/v0/b/heritage-site-edd7c.appspot.com/o/state%2FNAGALAND.jpg?alt=media&token=2a1add6a-4a88-487e-b68d-3798e5b8140f"
    }, {
        name: "odisha",
        capital: "bhubaneswar",
        imgurl: "https://firebasestorage.googleapis.com/v0/b/heritage-site-edd7c.appspot.com/o/state%2Fodisha.jpg?alt=media&token=371c3cc2-73d0-4d9c-b6d0-d1df4097f6e1"
    }, {
        name: "punjab",
        capital: "chandigarh",
        imgurl: "https://firebasestorage.googleapis.com/v0/b/heritage-site-edd7c.appspot.com/o/state%2Fpunjab.jpg?alt=media&token=9de307a5-6575-454b-8fcf-b24185f96d73"
    }, {
        name: "rajasthan",
        capital: "jaipur",
        imgurl: "https://firebasestorage.googleapis.com/v0/b/heritage-site-edd7c.appspot.com/o/state%2Frajsthan.jpg?alt=media&token=0545bf5a-d7a4-4262-b341-2d66588ac6db"
    }, {
        name: "sikkim",
        capital: "gangtok",
        imgurl: "https://firebasestorage.googleapis.com/v0/b/heritage-site-edd7c.appspot.com/o/state%2Fsikkim.jpg?alt=media&token=3b290d9c-29ae-4592-a9ba-c31180dccee6"
    }, {
        name: "tamilnadu",
        capital: "chennai",
        imgurl: "https://firebasestorage.googleapis.com/v0/b/heritage-site-edd7c.appspot.com/o/state%2Ftamilnadu.jpg?alt=media&token=851fbd5c-a304-44a7-91b0-e25aeafba3da"
    }, {
        name: "telangana",
        capital: "hyderabad",
        imgurl: "https://firebasestorage.googleapis.com/v0/b/heritage-site-edd7c.appspot.com/o/state%2Ftelengana.jpg?alt=media&token=ee7ae68a-8e97-41f8-a950-133073f59e42"
    }, {
        name: "tripura",
        capital: "agartala",
        imgurl: "https://firebasestorage.googleapis.com/v0/b/heritage-site-edd7c.appspot.com/o/state%2Ftripura.jpg?alt=media&token=dd1c5942-81d1-4cd5-abcb-c4b933f228bb"
    }, {
        name: "uttarpradesh",
        capital: "lucknow",
        imgurl: "https://firebasestorage.googleapis.com/v0/b/heritage-site-edd7c.appspot.com/o/state%2Futaarpradesh.jpg?alt=media&token=f8d877ef-c647-4443-9eb2-2297e2e831d1"
    }, {
        name: "uttarakhand",
        capital: "dehradun",
        imgurl: "https://firebasestorage.googleapis.com/v0/b/heritage-site-edd7c.appspot.com/o/state%2Futtarakhand.jpg?alt=media&token=a01c404d-c97f-44dd-ba15-9a79cb22593f"
    }, {
        name: "westbengal",
        capital: "kolkata",
        imgurl: "https://firebasestorage.googleapis.com/v0/b/heritage-site-edd7c.appspot.com/o/state%2Fwestbengal.jpg?alt=media&token=1b0efab0-efbb-4ddd-9483-f5a376efce5a"
    }
]
